import type { DomiServerContext } from '@/lib/domi/server-context';
import type { DomiToolDefinition, DomiToolName } from '@/lib/domi/tools/types';

const READ_TIMEOUT_MS = 8_000;
const ACTION_TIMEOUT_MS = 12_000;
const ALL_ROLES = ['customer', 'merchant', 'courier', 'admin'] as const;

export const DOMI_TOOL_REGISTRY: Record<DomiToolName, DomiToolDefinition> = {
  'customer.search_catalog': {
    name: 'customer.search_catalog',
    description: 'Busca negocios y productos activos del catálogo público.',
    roles: ['customer'],
    permissions: ['business.search', 'products.search'],
    riskLevel: 'low',
    requiresConfirmation: false,
    timeoutMs: READ_TIMEOUT_MS,
    idempotent: true,
  },
  'customer.cart_summary': {
    name: 'customer.cart_summary',
    description: 'Valida y resume el carrito del cliente con precios actuales del servidor.',
    roles: ['customer'],
    permissions: ['cart.read'],
    riskLevel: 'low',
    requiresConfirmation: false,
    timeoutMs: READ_TIMEOUT_MS,
    idempotent: true,
  },
  'customer.list_orders': {
    name: 'customer.list_orders',
    description: 'Consulta únicamente los pedidos del cliente autenticado.',
    roles: ['customer'],
    permissions: ['orders.read'],
    riskLevel: 'low',
    requiresConfirmation: false,
    timeoutMs: READ_TIMEOUT_MS,
    idempotent: true,
  },
  'customer.track_order': {
    name: 'customer.track_order',
    description: 'Consulta el seguimiento de un pedido perteneciente al cliente autenticado.',
    roles: ['customer'],
    permissions: ['orders.read'],
    riskLevel: 'low',
    requiresConfirmation: false,
    timeoutMs: READ_TIMEOUT_MS,
    idempotent: true,
  },
  'merchant.list_orders': {
    name: 'merchant.list_orders',
    description: 'Consulta pedidos pertenecientes al negocio autenticado.',
    roles: ['merchant'],
    permissions: ['orders.read'],
    riskLevel: 'low',
    requiresConfirmation: false,
    timeoutMs: READ_TIMEOUT_MS,
    idempotent: true,
  },
  'merchant.inventory_summary': {
    name: 'merchant.inventory_summary',
    description: 'Resume inventario y productos con existencias bajas del negocio autenticado.',
    roles: ['merchant'],
    permissions: ['inventory.read'],
    riskLevel: 'low',
    requiresConfirmation: false,
    timeoutMs: READ_TIMEOUT_MS,
    idempotent: true,
  },
  'merchant.sales_summary': {
    name: 'merchant.sales_summary',
    description: 'Calcula ventas verificadas del negocio autenticado.',
    roles: ['merchant'],
    permissions: ['reports.read'],
    riskLevel: 'low',
    requiresConfirmation: false,
    timeoutMs: READ_TIMEOUT_MS,
    idempotent: true,
  },
  'merchant.reviews_summary': {
    name: 'merchant.reviews_summary',
    description: 'Resume reseñas públicas asociadas al negocio autenticado.',
    roles: ['merchant'],
    permissions: ['reviews.read'],
    riskLevel: 'low',
    requiresConfirmation: false,
    timeoutMs: READ_TIMEOUT_MS,
    idempotent: true,
  },
  'merchant.update_order_status': {
    name: 'merchant.update_order_status',
    description: 'Prepara un cambio permitido de estado para un pedido del negocio.',
    roles: ['merchant'],
    permissions: ['orders.update'],
    riskLevel: 'medium',
    requiresConfirmation: true,
    timeoutMs: ACTION_TIMEOUT_MS,
    idempotent: true,
  },
  'merchant.update_product': {
    name: 'merchant.update_product',
    description: 'Prepara un cambio de estado o existencias para un producto del negocio.',
    roles: ['merchant'],
    permissions: ['inventory.update'],
    riskLevel: 'medium',
    requiresConfirmation: true,
    timeoutMs: ACTION_TIMEOUT_MS,
    idempotent: true,
  },
  'courier.available_orders': {
    name: 'courier.available_orders',
    description: 'Consulta pedidos disponibles sin revelar asignaciones de otros repartidores.',
    roles: ['courier'],
    permissions: ['assignments.read'],
    riskLevel: 'low',
    requiresConfirmation: false,
    timeoutMs: READ_TIMEOUT_MS,
    idempotent: true,
  },
  'courier.assignments': {
    name: 'courier.assignments',
    description: 'Consulta únicamente pedidos asignados al repartidor autenticado.',
    roles: ['courier'],
    permissions: ['assignments.read', 'delivery.read'],
    riskLevel: 'low',
    requiresConfirmation: false,
    timeoutMs: READ_TIMEOUT_MS,
    idempotent: true,
  },
  'courier.earnings_summary': {
    name: 'courier.earnings_summary',
    description: 'Resume ganancias del repartidor autenticado.',
    roles: ['courier'],
    permissions: ['earnings.read'],
    riskLevel: 'low',
    requiresConfirmation: false,
    timeoutMs: READ_TIMEOUT_MS,
    idempotent: true,
  },
  'courier.delivery_history': {
    name: 'courier.delivery_history',
    description: 'Consulta entregas completadas por el repartidor autenticado.',
    roles: ['courier'],
    permissions: ['delivery.read'],
    riskLevel: 'low',
    requiresConfirmation: false,
    timeoutMs: READ_TIMEOUT_MS,
    idempotent: true,
  },
  'courier.accept_order': {
    name: 'courier.accept_order',
    description: 'Prepara la asignación de un pedido disponible al repartidor autenticado.',
    roles: ['courier'],
    permissions: ['assignments.accept'],
    riskLevel: 'medium',
    requiresConfirmation: true,
    timeoutMs: ACTION_TIMEOUT_MS,
    idempotent: true,
  },
  'courier.update_order_status': {
    name: 'courier.update_order_status',
    description: 'Prepara un avance permitido del pedido asignado al repartidor.',
    roles: ['courier'],
    permissions: ['delivery.update'],
    riskLevel: 'medium',
    requiresConfirmation: true,
    timeoutMs: ACTION_TIMEOUT_MS,
    idempotent: true,
  },
  'admin.platform_metrics': {
    name: 'admin.platform_metrics',
    description: 'Consulta métricas agregadas de operación sin exportar datos personales.',
    roles: ['admin'],
    permissions: ['operation.read', 'reports.read'],
    riskLevel: 'low',
    requiresConfirmation: false,
    timeoutMs: READ_TIMEOUT_MS,
    idempotent: true,
  },
  'admin.order_summary': {
    name: 'admin.order_summary',
    description: 'Resume estados y pedidos potencialmente detenidos de la plataforma.',
    roles: ['admin'],
    permissions: ['orders.read'],
    riskLevel: 'low',
    requiresConfirmation: false,
    timeoutMs: READ_TIMEOUT_MS,
    idempotent: true,
  },
  'admin.business_summary': {
    name: 'admin.business_summary',
    description: 'Consulta estado agregado de negocios sin exponer secretos.',
    roles: ['admin'],
    permissions: ['business.read'],
    riskLevel: 'low',
    requiresConfirmation: false,
    timeoutMs: READ_TIMEOUT_MS,
    idempotent: true,
  },
  'admin.courier_summary': {
    name: 'admin.courier_summary',
    description: 'Consulta estado operativo agregado de repartidores.',
    roles: ['admin'],
    permissions: ['courier.read'],
    riskLevel: 'low',
    requiresConfirmation: false,
    timeoutMs: READ_TIMEOUT_MS,
    idempotent: true,
  },
  'admin.audit_summary': {
    name: 'admin.audit_summary',
    description: 'Consulta eventos recientes de auditoría con datos limitados.',
    roles: ['admin'],
    permissions: ['audit.read'],
    riskLevel: 'low',
    requiresConfirmation: false,
    timeoutMs: READ_TIMEOUT_MS,
    idempotent: true,
  },
  'memory.list': {
    name: 'memory.list',
    description: 'Lista únicamente los recuerdos personales del usuario autenticado.',
    roles: ALL_ROLES,
    permissions: ['memory.manage'],
    riskLevel: 'low',
    requiresConfirmation: false,
    timeoutMs: READ_TIMEOUT_MS,
    idempotent: true,
  },
  'memory.set_enabled': {
    name: 'memory.set_enabled',
    description: 'Prepara la activación o desactivación de la memoria personal de Domi.',
    roles: ALL_ROLES,
    permissions: ['memory.manage'],
    riskLevel: 'medium',
    requiresConfirmation: true,
    timeoutMs: ACTION_TIMEOUT_MS,
    idempotent: true,
  },
  'memory.delete_all': {
    name: 'memory.delete_all',
    description: 'Prepara la eliminación permanente de todos los recuerdos personales.',
    roles: ALL_ROLES,
    permissions: ['memory.manage'],
    riskLevel: 'medium',
    requiresConfirmation: true,
    timeoutMs: ACTION_TIMEOUT_MS,
    idempotent: true,
  },
  'support.create_ticket': {
    name: 'support.create_ticket',
    description: 'Prepara un ticket de soporte para el usuario autenticado.',
    roles: ALL_ROLES,
    permissions: ['support.create'],
    riskLevel: 'medium',
    requiresConfirmation: true,
    timeoutMs: ACTION_TIMEOUT_MS,
    idempotent: true,
  },
  'action.confirm': {
    name: 'action.confirm',
    description: 'Confirma y ejecuta una acción pendiente perteneciente al usuario autenticado.',
    roles: ALL_ROLES,
    permissions: [],
    riskLevel: 'medium',
    requiresConfirmation: false,
    timeoutMs: ACTION_TIMEOUT_MS,
    idempotent: true,
  },
  'action.cancel': {
    name: 'action.cancel',
    description: 'Cancela una acción pendiente perteneciente al usuario autenticado.',
    roles: ALL_ROLES,
    permissions: [],
    riskLevel: 'low',
    requiresConfirmation: false,
    timeoutMs: READ_TIMEOUT_MS,
    idempotent: true,
  },
};

export function canExecuteDomiTool(context: DomiServerContext, name: DomiToolName) {
  const definition = DOMI_TOOL_REGISTRY[name];
  return Boolean(
    definition
      && definition.roles.includes(context.role)
      && definition.permissions.every((permission) => context.permissions.includes(permission)),
  );
}

export async function withDomiToolTimeout<T>(name: DomiToolName, operation: () => Promise<T>): Promise<T> {
  const timeoutMs = DOMI_TOOL_REGISTRY[name]?.timeoutMs || READ_TIMEOUT_MS;
  let timeoutId: ReturnType<typeof setTimeout> | undefined;
  try {
    return await Promise.race([
      operation(),
      new Promise<T>((_, reject) => {
        timeoutId = setTimeout(() => reject(new Error(`domi_tool_timeout:${name}`)), timeoutMs);
      }),
    ]);
  } finally {
    if (timeoutId) clearTimeout(timeoutId);
  }
}
