'use client';

import React, { useEffect, useState } from 'react';
import { useAuth } from '@/contexts/AuthContext';
import { businessService, type BusinessOrder } from '@/services/business';
import { SkeletonList } from '@/components/ui/skeleton';
import { OrderCustomizationDetails } from '@/components/business/order-customization-details';
import { ClipboardList, MapPin, User, Package } from 'lucide-react';

const COLUMNS = [
  { key: 'pending', label: 'Pendiente' }, { key: 'confirmed', label: 'Confirmado' }, { key: 'preparing', label: 'Preparando' }, { key: 'ready', label: 'Listo' }, { key: 'assigned', label: 'Asignado' }, { key: 'in_transit', label: 'En camino' }, { key: 'delivered', label: 'Entregado' },
];
const STATUS_FLOW: Record<string, string> = { pending: 'confirmed', confirmed: 'preparing', preparing: 'ready', ready: 'assigned', assigned: 'in_transit', in_transit: 'delivered' };
const formatCurrency = (value: number) => '$' + Number(value).toLocaleString('es-CO');

export default function NegocioPedidos() {
  const { profile } = useAuth(); const [orders, setOrders] = useState<BusinessOrder[]>([]); const [loading, setLoading] = useState(true); const [selected, setSelected] = useState<string | null>(null);
  const loadOrders = async () => { if (!profile?.id) return; const businessId = await businessService.getBusinessId(profile.id); if (businessId) setOrders(await businessService.getBusinessOrders(businessId)); };
  useEffect(() => { void (async () => { await loadOrders(); setLoading(false); })(); }, [profile?.id]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => { const timer = setInterval(() => void loadOrders(), 10000); return () => clearInterval(timer); }, [profile?.id]); // eslint-disable-line react-hooks/exhaustive-deps
  const changeStatus = async (orderId: string, status: string) => { const { getBrowserClient } = await import('@/lib/db/supabase'); const client = await getBrowserClient(); await client.from('orders').update({ status } as never).eq('id', orderId); setOrders((current) => current.map((order) => order.id === orderId ? { ...order, status } : order)); };
  if (loading) return <SkeletonList />;
  return <div className="space-y-6"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-bold">Pedidos</h1><p className="text-sm text-muted-foreground">Cada pedido incluye estilo, salsas, presentación, adicionales y notas.</p></div><button onClick={() => void loadOrders()} className="rounded-xl border px-3 py-2 text-sm">Actualizar</button></div><div className="flex gap-4 overflow-x-auto pb-4">{COLUMNS.map((column) => { const columnOrders = orders.filter((order) => order.status === column.key); return <section key={column.key} className="min-w-[290px] rounded-2xl border bg-card"><header className="flex items-center justify-between border-b p-3"><h2 className="font-semibold">{column.label}</h2><span className="rounded-full bg-muted px-2 text-xs">{columnOrders.length}</span></header><div className="space-y-3 p-3">{columnOrders.length === 0 ? <div className="py-8 text-center text-xs text-muted-foreground"><ClipboardList className="mx-auto mb-2 h-5 w-5" />Vacío</div> : columnOrders.map((order) => <article key={order.id} className="rounded-xl border p-3"><button onClick={() => setSelected(selected === order.id ? null : order.id)} className="w-full text-left"><div className="flex justify-between"><strong className="text-sm">#{order.order_number}</strong><strong className="text-sm">{formatCurrency(order.total_amount)}</strong></div><p className="text-xs text-muted-foreground">{order.customer_name}</p></button><div className="mt-2 flex gap-2">{STATUS_FLOW[order.status] && <button onClick={() => void changeStatus(order.id, STATUS_FLOW[order.status])} className="flex-1 rounded-lg bg-primary/10 py-2 text-xs font-semibold text-primary">{order.status === 'pending' ? 'Confirmar' : order.status === 'confirmed' ? 'Preparar' : order.status === 'preparing' ? 'Marcar listo' : 'Avanzar'}</button>}{order.status === 'pending' && <button onClick={() => void changeStatus(order.id, 'cancelled')} className="rounded-lg bg-destructive/10 px-3 text-xs text-destructive">Rechazar</button>}</div>{selected === order.id && <div className="mt-3 border-t pt-3"><p className="text-xs text-muted-foreground"><MapPin className="mr-1 inline h-3 w-3" />{order.delivery_address || 'Dirección pendiente'}</p>{order.special_instructions && <p className="mt-1 text-xs text-muted-foreground"><Package className="mr-1 inline h-3 w-3" />{order.special_instructions}</p>}{order.courier_name && <p className="mt-1 text-xs text-muted-foreground"><User className="mr-1 inline h-3 w-3" />{order.courier_name}</p>}<OrderCustomizationDetails orderId={order.id} /></div>}</article>)}</div></section>; })}</div></div>;
}
