'use client';

import React from 'react';
import { PageContainer } from '@/components/ui/page-container';
import { EmptyState } from '@/components/ui/empty-state';
import { useCart } from '@/contexts/CartContext';
import { ShoppingBag, Trash2, Plus, Minus, ArrowLeft } from 'lucide-react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';

export default function CartPage() {
  const router = useRouter(); const { items, businessName, subtotal, isEmpty, removeItem, updateQuantity, clearCart } = useCart();
  if (isEmpty) return <PageContainer><EmptyState icon={<ShoppingBag className="h-6 w-6" />} title="Tu carrito está vacío" description="Agrega productos para comenzar." action={<Link href="/cliente">Ver restaurantes</Link>} /></PageContainer>;
  return <div className="min-h-screen bg-background pb-36"><header className="sticky top-0 z-30 border-b bg-background/90"><div className="mx-auto flex h-14 max-w-6xl items-center gap-3 px-4"><button onClick={() => router.back()}><ArrowLeft className="h-5 w-5" /></button><span className="font-semibold">Carrito — {businessName}</span><button onClick={clearCart} className="ml-auto text-sm text-destructive">Vaciar</button></div></header><PageContainer><div className="space-y-3">{items.map((item) => <article key={item.id} className="rounded-2xl border p-4"><div className="flex items-start justify-between gap-4"><div className="min-w-0 flex-1"><h3 className="font-semibold">{item.product.name}</h3><p className="text-sm text-muted-foreground">${item.unitPrice.toLocaleString('es-CO')} c/u</p>{item.customization?.style && <p className="mt-2 text-xs text-muted-foreground"><strong>Estilo:</strong> {item.customization.style}</p>}{item.customization?.sauces?.length ? <p className="text-xs text-muted-foreground"><strong>Salsas:</strong> {item.customization.sauces.join(', ')}</p> : null}{item.customization?.saucePresentation && <p className="text-xs text-muted-foreground"><strong>Presentación:</strong> {item.customization.saucePresentation === 'aparte' ? 'Salsas aparte' : 'Alitas bañadas'}</p>}{item.customization?.extras?.length ? <p className="text-xs text-muted-foreground"><strong>Adicionales:</strong> {item.customization.extras.map((extra) => `${extra.quantity}x ${extra.name}`).join(', ')}</p> : null}{item.customization?.preparationNote && <p className="text-xs text-muted-foreground"><strong>Nota:</strong> {item.customization.preparationNote}</p>}</div><button onClick={() => removeItem(item.id)} className="text-destructive"><Trash2 className="h-4 w-4" /></button></div><div className="mt-4 flex items-center justify-between"><div className="flex items-center gap-2"><button onClick={() => item.quantity <= 1 ? removeItem(item.id) : updateQuantity(item.id, item.quantity - 1)} className="rounded-lg border p-2"><Minus className="h-4 w-4" /></button><span className="w-7 text-center font-bold">{item.quantity}</span><button onClick={() => updateQuantity(item.id, item.quantity + 1)} className="rounded-lg bg-primary p-2 text-primary-foreground"><Plus className="h-4 w-4" /></button></div><strong>${(item.unitPrice * item.quantity).toLocaleString('es-CO')}</strong></div></article>)}</div></PageContainer><div className="fixed bottom-16 left-0 right-0 border-t bg-background/95 p-4 lg:bottom-0"><div className="mx-auto max-w-6xl"><div className="mb-3 flex justify-between text-lg font-bold"><span>Total</span><span>${subtotal.toLocaleString('es-CO')}</span></div><Link href="/cliente/checkout" className="block rounded-2xl bg-primary py-4 text-center font-bold text-primary-foreground">Continuar</Link></div></div></div>;
}
